In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("titanic.csv")
data.head(50)

PassengerId  Survived  Pclass           Lname  \
0             1         0       3          Braund   
1             2         1       1         Cumings   
2             3         1       3       Heikkinen   
3             4         1       1        Futrelle   
4             5         0       3           Allen   
5             6         0       3           Moran   
6             7         0       1        McCarthy   
7             8         0       3         Palsson   
8             9         1       3         Johnson   
9            10         1       2          Nasser   
10           11         1       3       Sandstrom   
11           12         1       1         Bonnell   
12           13         0       3     Saundercock   
13           14         0       3       Andersson   
14           15         0       3         Vestrom   
15           16         1       2         Hewlett   
16           17         0       3            Rice   
17           18         1       2        Williams   
18           19         0       3   Vander Planke   
19           20         1       3      Masselmani   
20           21         0       2          Fynney   
21           22         1       2         Beesley   
22           23         1       3         McGowan   
23           24         1       1          Sloper   
24           25         0       3         Palsson   
25           26         1       3         Asplund   
26           27         0       3            Emir   
27           28         0       1         Fortune   
28           29         1       3         O'Dwyer   
29           30         0       3        Todoroff   
30           31         0       1       Uruchurtu   
31           32         1       1         Spencer   
32           33         1       3           Glynn   
33           34         0       2         Wheadon   
34           35         0       1           Meyer   
35           36         0       1       Holverson   
36           37         1       3           Mamee   
37           38         0       3            Cann   
38           39         0       3   Vander Planke   
39           40         1       3   Nicola-Yarred   
40           41         0       3           Ahlin   
41           42         0       2          Turpin   
42           43         0       3          Kraeff   
43           44         1       2         Laroche   
44           45         1       3         Devaney   
45           46         0       3          Rogers   
46           47         0       3          Lennon   
47           48         1       3      O'Driscoll   
48           49         0       3          Samaan   
49           50         0       3  Arnold-Franchi   

                                                 Name     Sex   Age  SibSp  \
0                                     Mr. Owen Harris    male  22.0      1   
1          Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                                         Miss. Laina  female  26.0      0   
3                  Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                                   Mr. William Henry    male  35.0      0   
5                                           Mr. James    male   NaN      0   
6                                       Mr. Timothy J    male  54.0      0   
7                               Master. Gosta Leonard    male   2.0      3   
8            Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                         Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                               Miss. Marguerite Rut  female   4.0      1   
11                                    Miss. Elizabeth  female  58.0      0   
12                                  Mr. William Henry    male  20.0      0   
13                                   Mr. Anders Johan    male  39.0      1   
14                        Miss. Hulda Amanda Adolfina  female  14.0      0   
15                            Mrs. (Mary D Kingcome)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  156 non-null    int64  
 1   Survived     156 non-null    int64  
 2   Pclass       156 non-null    int64  
 3   Lname        156 non-null    object 
 4   Name         156 non-null    object 
 5   Sex          156 non-null    object 
 6   Age          126 non-null    float64
 7   SibSp        156 non-null    int64  
 8   Parch        156 non-null    int64  
 9   Ticket       156 non-null    object 
 10  Fare         156 non-null    float64
 11  Cabin        31 non-null     object 
 12  Embarked     155 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 16.0+ KB


In [4]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Lname', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
data.columns=['passengerid', 'survived', 'pclass', 'lastname', 'name', 'sex', 'age',
       'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  156 non-null    int64  
 1   survived     156 non-null    int64  
 2   pclass       156 non-null    int64  
 3   lastname     156 non-null    object 
 4   name         156 non-null    object 
 5   sex          156 non-null    object 
 6   age          126 non-null    float64
 7   sibsp        156 non-null    int64  
 8   parch        156 non-null    int64  
 9   ticket       156 non-null    object 
 10  fare         156 non-null    float64
 11  cabin        31 non-null     object 
 12  embarked     155 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 16.0+ KB


In [7]:
data.isna().sum()

passengerid      0
survived         0
pclass           0
lastname         0
name             0
sex              0
age             30
sibsp            0
parch            0
ticket           0
fare             0
cabin          125
embarked         1
dtype: int64

In [8]:
# median method to impute missing value 
data["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [9]:
age_median = data["age"].median()
age_median

26.0

In [10]:
data["age"]=data["age"].fillna(age_median)

In [11]:
data.isna().sum()

passengerid      0
survived         0
pclass           0
lastname         0
name             0
sex              0
age              0
sibsp            0
parch            0
ticket           0
fare             0
cabin          125
embarked         1
dtype: int64

In [12]:
data.drop(["cabin"],axis=1,inplace=True)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  156 non-null    int64  
 1   survived     156 non-null    int64  
 2   pclass       156 non-null    int64  
 3   lastname     156 non-null    object 
 4   name         156 non-null    object 
 5   sex          156 non-null    object 
 6   age          156 non-null    float64
 7   sibsp        156 non-null    int64  
 8   parch        156 non-null    int64  
 9   ticket       156 non-null    object 
 10  fare         156 non-null    float64
 11  embarked     155 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB


In [14]:
import warnings
warnings.filterwarnings("ignore")

In [15]:
embarked_mode=data["embarked"].value_counts()[1]
embarked_mode

32

In [16]:
data["embarked"]=data["embarked"].fillna(embarked_mode)

In [17]:
data.isna().sum()

passengerid    0
survived       0
pclass         0
lastname       0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
embarked       0
dtype: int64

In [18]:
clean_data=data.drop(["survived","lastname","name","ticket","passengerid"],axis=1)

In [19]:
clean_data["family_size"]=clean_data["sibsp"] + clean_data["parch"]+ 1

In [20]:
clean_data=clean_data.drop(["sibsp","parch"],axis=1)

In [21]:
dummy_variables=pd.get_dummies(clean_data,drop_first=True,dtype=int)

In [22]:
dummy_variables

pclass   age     fare  family_size  sex_male  embarked_C  embarked_Q  \
0         3  22.0   7.2500            2         1           0           0   
1         1  38.0  71.2833            2         0           1           0   
2         3  26.0   7.9250            1         0           0           0   
3         1  35.0  53.1000            2         0           0           0   
4         3  35.0   8.0500            1         1           0           0   
..      ...   ...      ...          ...       ...         ...         ...   
151       1  22.0  66.6000            2         0           0           0   
152       3  55.5   8.0500            1         1           0           0   
153       3  40.5  14.5000            3         1           0           0   
154       3  26.0   7.3125            1         1           0           0   
155       1  51.0  61.3792            2         1           1           0   

     embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
151           1  
152           1  
153           1  
154           1  
155           0  

[156 rows x 8 columns]

In [25]:
x= dummy_variables
x

pclass   age     fare  family_size  sex_male  embarked_C  embarked_Q  \
0         3  22.0   7.2500            2         1           0           0   
1         1  38.0  71.2833            2         0           1           0   
2         3  26.0   7.9250            1         0           0           0   
3         1  35.0  53.1000            2         0           0           0   
4         3  35.0   8.0500            1         1           0           0   
..      ...   ...      ...          ...       ...         ...         ...   
151       1  22.0  66.6000            2         0           0           0   
152       3  55.5   8.0500            1         1           0           0   
153       3  40.5  14.5000            3         1           0           0   
154       3  26.0   7.3125            1         1           0           0   
155       1  51.0  61.3792            2         1           1           0   

     embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
151           1  
152           1  
153           1  
154           1  
155           0  

[156 rows x 8 columns]

In [30]:
y=data["survived"]
y

0      0
1      1
2      1
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: survived, Length: 156, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=243,shuffle=True)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(124, 8)
(32, 8)
(124,)
(32,)


In [39]:
from sklearn.linear_model import LogisticRegression

In [41]:
model=LogisticRegression()
model

LogisticRegression()

In [42]:
model.fit(x_train,y_train)

LogisticRegression()

In [58]:
y_pred=model.predict(x_test)

In [59]:
x_test.columns

Index(['pclass', 'age', 'fare', 'family_size', 'sex_male', 'embarked_C',
       'embarked_Q', 'embarked_S'],
      dtype='object')

In [60]:
model.predict([[2,34,5000,4,0,1,0,0]])

array([0], dtype=int64)

In [61]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [67]:
confusion_matrix(y_pred,y_test)

array([[19,  3],
       [ 4,  6]], dtype=int64)

In [66]:
pd.DataFrame(data=confusion_matrix(y_pred,y_test),columns=["Actual Negative","ActualPositive"],index=["Predicted Negative","Predicted Positive"])

Actual Negative  ActualPositive
Predicted Negative               19               3
Predicted Positive                4               6

In [84]:
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score

In [85]:
accuracy_score(y_pred,y_test)

0.78125

In [86]:
f1_score(y_pred,y_test)

0.631578947368421

In [88]:
recall_score(y_pred,y_test)


0.6

In [89]:
precision_score(y_pred,y_test)

0.6666666666666666

In [70]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84        22
           1       0.67      0.60      0.63        10

    accuracy                           0.78        32
   macro avg       0.75      0.73      0.74        32
weighted avg       0.78      0.78      0.78        32



In [71]:
x_test.shape

(32, 8)

In [74]:
model.predict([[2,34,5000,4,0,1,0,0]])

array([0], dtype=int64)

In [81]:
import pickle
pickle.dump(model,open("mymodel1.pkl","wb"))